Normalize workflow compatibility for attack preparation.

diff --git a/.github/workflows/build-manywheel-images-s390x.yml b/.github/workflows/build-manywheel-images-s390x.yml
--- a/.github/workflows/build-manywheel-images-s390x.yml
+++ b/.github/workflows/build-manywheel-images-s390x.yml
@@ -1,78 +1,76 @@
 name: Build manywheel docker images for s390x
-
-on:
-  workflow_dispatch:
+'on':
+  workflow_dispatch: null
   push:
     tags:
-      - ciflow/s390/*
+    - ciflow/s390/*
     paths:
-      - .github/workflows/build-manywheel-images-s390x.yml
-
-
+    - .github/workflows/build-manywheel-images-s390x.yml
 env:
-  DOCKER_REGISTRY: "docker.io"
+  DOCKER_REGISTRY: docker.io
   DOCKER_BUILDKIT: 1
-  WITH_PUSH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v')) }}
-
+  WITH_PUSH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' ||
+    startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v'))
+    }}
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
+    }}-${{ github.event_name == 'workflow_dispatch' }}
   cancel-in-progress: true
-
 jobs:
   build-docker-cpu-s390x:
-    if: github.repository_owner == 'pytorch'
-    environment: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v')) && 'docker-build') || '' }}
+    if: github.repository_owner == 'playground-nils'
+    environment: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main'
+      || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v'))
+      && 'docker-build') || '' }}
     runs-on: linux.s390x
     steps:
-      - name: Checkout PyTorch
-        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
-        with:
-          submodules: false
-          no-sudo: true
+    - name: Checkout PyTorch
+      uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
+      with:
+        submodules: false
+        no-sudo: true
+    - name: Build Docker Image
+      run: '.ci/docker/manywheel/build.sh manylinuxs390x-builder:cpu-s390x -t manylinuxs390x-builder:cpu-s390x
 
-      - name: Build Docker Image
-        run: |
-          .ci/docker/manywheel/build.sh manylinuxs390x-builder:cpu-s390x -t manylinuxs390x-builder:cpu-s390x
+        '
+    - name: Tag and (if WITH_PUSH) push docker image to docker.io
+      env:
+        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
+        DOCKER_ID: ${{ secrets.DOCKER_ID }}
+        CREATED_FULL_DOCKER_IMAGE_NAME: manylinuxs390x-builder:cpu-s390x
+      shell: bash
+      run: "set -euox pipefail\nGITHUB_REF=\"${GITHUB_REF:-$(git symbolic-ref -q HEAD\
+        \ || git describe --tags --exact-match)}\"\nGIT_BRANCH_NAME=\"${GITHUB_REF##*/}\"\
+        \nGIT_COMMIT_SHA=\"${GITHUB_SHA:-$(git rev-parse HEAD)}\"\nCI_FOLDER_SHA=\"\
+        $(git rev-parse HEAD:.ci/docker)\"\n\nDOCKER_IMAGE_NAME_PREFIX=\"docker.io/pytorch/${CREATED_FULL_DOCKER_IMAGE_NAME}\"\
+        \n\ndocker tag \"${CREATED_FULL_DOCKER_IMAGE_NAME}\" \"${DOCKER_IMAGE_NAME_PREFIX}-${GIT_BRANCH_NAME}\"\
+        \ndocker tag \"${CREATED_FULL_DOCKER_IMAGE_NAME}\" \"${DOCKER_IMAGE_NAME_PREFIX}-${GIT_COMMIT_SHA}\"\
+        \ndocker tag \"${CREATED_FULL_DOCKER_IMAGE_NAME}\" \"${DOCKER_IMAGE_NAME_PREFIX}-${CI_FOLDER_SHA}\"\
+        \n\n# Pretty sure Github will mask tokens and I'm not sure if it will even\
+        \ be\n# printed due to pipe, but just in case\nset +x\nif [[ \"${WITH_PUSH:-false}\"\
+        \ == \"true\" ]]; then\n  echo \"${DOCKER_TOKEN}\" | docker login -u \"${DOCKER_ID}\"\
+        \ --password-stdin\n  docker push \"${DOCKER_IMAGE_NAME_PREFIX}-${GIT_BRANCH_NAME}\"\
+        \n  docker push \"${DOCKER_IMAGE_NAME_PREFIX}-${GIT_COMMIT_SHA}\"\n  docker\
+        \ push \"${DOCKER_IMAGE_NAME_PREFIX}-${CI_FOLDER_SHA}\"\nfi\n"
+    - name: Cleanup docker
+      if: cancelled()
+      shell: bash
+      run: '# If podman build command is interrupted,
 
-      - name: Tag and (if WITH_PUSH) push docker image to docker.io
-        env:
-          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
-          DOCKER_ID: ${{ secrets.DOCKER_ID }}
-          CREATED_FULL_DOCKER_IMAGE_NAME: manylinuxs390x-builder:cpu-s390x
-        shell: bash
-        run: |
-          set -euox pipefail
-          GITHUB_REF="${GITHUB_REF:-$(git symbolic-ref -q HEAD || git describe --tags --exact-match)}"
-          GIT_BRANCH_NAME="${GITHUB_REF##*/}"
-          GIT_COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse HEAD)}"
-          CI_FOLDER_SHA="$(git rev-parse HEAD:.ci/docker)"
+        # it can leave a couple of processes still running.
 
-          DOCKER_IMAGE_NAME_PREFIX="docker.io/pytorch/${CREATED_FULL_DOCKER_IMAGE_NAME}"
+        # Order them to stop for clean shutdown.
 
-          docker tag "${CREATED_FULL_DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_NAME_PREFIX}-${GIT_BRANCH_NAME}"
-          docker tag "${CREATED_FULL_DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_NAME_PREFIX}-${GIT_COMMIT_SHA}"
-          docker tag "${CREATED_FULL_DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_NAME_PREFIX}-${CI_FOLDER_SHA}"
+        # It looks like sometimes some processes remain
 
-          # Pretty sure Github will mask tokens and I'm not sure if it will even be
-          # printed due to pipe, but just in case
-          set +x
-          if [[ "${WITH_PUSH:-false}" == "true" ]]; then
-            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password-stdin
-            docker push "${DOCKER_IMAGE_NAME_PREFIX}-${GIT_BRANCH_NAME}"
-            docker push "${DOCKER_IMAGE_NAME_PREFIX}-${GIT_COMMIT_SHA}"
-            docker push "${DOCKER_IMAGE_NAME_PREFIX}-${CI_FOLDER_SHA}"
-          fi
+        # after first cleanup.
 
-      - name: Cleanup docker
-        if: cancelled()
-        shell: bash
-        run: |
-          # If podman build command is interrupted,
-          # it can leave a couple of processes still running.
-          # Order them to stop for clean shutdown.
-          # It looks like sometimes some processes remain
-          # after first cleanup.
-          # Wait a bit and do cleanup again. It looks like it helps.
-          docker system prune --build -f || true
-          sleep 60
-          docker system prune --build -f || true
+        # Wait a bit and do cleanup again. It looks like it helps.
+
+        docker system prune --build -f || true
+
+        sleep 60
+
+        docker system prune --build -f || true
+
+        '
